Изменена форма выбра языка
Gray-Advantage/Datanar-Django pull request #53
Opened 2024-11-02 18:45 UTC by brandonzorn

Изменена форма выбра языка
![изображение](https://github.com/user-attachments/assets/b30e935b-0ed7-40cc-a215-53ef7a84aa47)

2024-11-02 18:48 UTC, Gray-Advantage commented
Не жданно не гаданно

Пару минут)

2024-11-02 19:10 UTC, Gray-Advantage requested changes
В целом прикольно, но:

- Обнови версию в settings.
- Лучше оставить Celery версии 5.0.0, так как более новые версии при нативной установке не поддерживаются (на windows). При этом "небезопасность" версии 5.0.0 не представляет проблемы, поскольку у нас нечего ломать: независимо от того, что пользователь отправляет, программа только ищет ссылки и заменяет их на сокращенные.
- Сокращенный языковой код (RU, JA b тд) выглядит стильно, но он представлен только латиницей, что кажется странным. Например, весь сайт может быть на японском, а переключатель — на латинице. Я бы оставил полные названия языков.
- А ну даже на скрине видно, что нужно небольшое расстояние меж списком и кнопкой "Войти"

А так круто, что иногда приходишь и что-то вносишь в проект)

2024-11-03 09:43 UTC, brandonzorn commented
> В целом прикольно, но:
> 
>     * Обнови версию в settings.
> 
>     * Лучше оставить Celery версии 5.0.0, так как более новые версии при нативной установке не поддерживаются (на windows). При этом "небезопасность" версии 5.0.0 не представляет проблемы, поскольку у нас нечего ломать: независимо от того, что пользователь отправляет, программа только ищет ссылки и заменяет их на сокращенные.
> 
>     * Сокращенный языковой код (RU, JA b тд) выглядит стильно, но он представлен только латиницей, что кажется странным. Например, весь сайт может быть на японском, а переключатель — на латинице. Я бы оставил полные названия языков.
> 
>     * А ну даже на скрине видно, что нужно небольшое расстояние меж списком и кнопкой "Войти"
> 
> 
> А так круто, что иногда приходишь и что-то вносишь в проект)

Исправил

2024-11-03 11:13 UTC, Gray-Advantage commented
Во, теперь всё круто!

2024-11-03 11:14 UTC, Gray-Advantage approved these changes
Всё хорошо!

2024-11-03 11:15 UTC, merged